spring:
  application:
    name: Passbook
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/passbook?autoReconnect=true
    username: root
    password: 123456
  kafka:
    bootstrap-servers: 192.168.31.69:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4
  data:
    hbase:
      quorum: 192.168.31.69:2181
      rootDir: ﻿hdfs://192.168.31.69:9000/hbase
      nodeParent: /hbase
  redis:
    host: 192.168.1.105
    port: 6379



server:
  port: 9528

logging:
  file: imooc-passbook.log
  level: debug



